In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!cp -r '/content/drive/MyDrive/Leaf Cropped Images' leaf_cropped_images 

In [5]:
!tfds new leaf_classification

2022-11-17 09:20:04.639830: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Dataset generated at /content/leaf_classification
You can start searching `TODO(leaf_classification)` to complete the implementation.
Please check https://www.tensorflow.org/datasets/add_dataset for additional details.


In [12]:
!mkdir full

In [13]:
!mv leaf_cropped_images full/leaf_cropped_images

In [14]:
import tensorflow_datasets as tfds
builder = tfds.ImageFolder('full')
print(builder.info)  # num examples, labels... are automatically calculated
ds = builder.as_dataset(split='leaf_cropped_images', shuffle_files=True)
# tfds.show_examples(ds, builder.info)

tfds.core.DatasetInfo(
    name='image_folder',
    full_name='image_folder/1.0.0',
    description="""
    Generic image classification dataset.
    """,
    homepage='https://www.tensorflow.org/datasets/catalog/image_folder',
    data_path='full',
    file_format=tfrecord,
    download_size=Unknown size,
    dataset_size=Unknown size,
    features=FeaturesDict({
        'image': Image(shape=(None, None, 3), dtype=tf.uint8),
        'image/filename': Text(shape=(), dtype=tf.string),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=15),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'leaf_cropped_images': <SplitInfo num_examples=7585, num_shards=1>,
    },
    citation="""""",
)


In [15]:
for data in ds:
  print(data)
  break

{'image': <tf.Tensor: shape=(1298, 1270, 3), dtype=uint8, numpy=
array([[[ 84, 126, 106],
        [ 84, 127, 108],
        [ 83, 126, 107],
        ...,
        [137, 164, 145],
        [138, 163, 144],
        [139, 164, 143]],

       [[ 84, 127, 107],
        [ 83, 128, 107],
        [ 81, 129, 107],
        ...,
        [138, 163, 144],
        [137, 161, 145],
        [141, 166, 147]],

       [[ 84, 129, 109],
        [ 83, 126, 106],
        [ 83, 126, 107],
        ...,
        [139, 164, 145],
        [142, 167, 148],
        [142, 167, 146]],

       ...,

       [[ 85, 139, 107],
        [ 86, 140, 108],
        [ 85, 138, 108],
        ...,
        [129, 117,  91],
        [129, 117,  93],
        [128, 118,  93]],

       [[ 87, 138, 107],
        [ 86, 137, 104],
        [ 87, 138, 107],
        ...,
        [129, 117,  95],
        [129, 118,  96],
        [126, 118,  95]],

       [[ 86, 137, 106],
        [ 85, 136, 103],
        [ 87, 138, 107],
        ...,
        [

In [26]:
pp = '/content/full/leaf_cropped_images/croped_Calcarious soil symptoms/'
pp

'/content/full/leaf_cropped_images/croped_Calcarious soil symptoms'

In [27]:
import os
os.path.basename(os.path.normpath(pp))

'croped_Calcarious soil symptoms'

In [29]:
len(os.listdir('full/leaf_cropped_images'))

15

In [185]:
cd ..

/


In [186]:
cd leaf_classification

/content/leaf_classification


In [187]:
!tfds build

2022-11-17 12:02:10.881395: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
INFO[build.py]: Loading dataset  from path: /content/leaf_classification/leaf_classification.py
2022-11-17 12:02:11.003191: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "NOT_FOUND: Error executing an HTTP request: HTTP response code 404".
INFO[build.py]: download_and_prepare for dataset leaf_classification/1.0.0...
INFO[dataset_builder.py]: Generating dataset leaf_classification (/root/tensorflow_datasets/leaf_classification/1.0.0)
Generating splits...:   0% 0/1 [00:00<?, ? splits/s]
Generating leaf_cropped_images examples...: 0 examples [00:00, ? examples/s]
Traceback (most recent call last)

In [176]:
cd  /root/tensorflow_datasets/leaf_classification/

/root/tensorflow_datasets/leaf_classification


In [178]:
# rm -r 1.0.0 1.0.1 2.0.0

In [172]:
import leaf_classification  # Register `my_dataset`

ds, ds_info = tfds.load('leaf_classification:1.0.1', split='test_images', with_info=True)

In [175]:
ds_info

tfds.core.DatasetInfo(
    name='leaf_classification',
    full_name='leaf_classification/1.0.1',
    description="""
    Description is **formatted** as markdown.
    
    It should also contain any processing which has been applied (if any),
    (e.g. corrupted example skipped, images cropped,...):
    """,
    homepage='https://dataset-homepage/',
    data_path='/root/tensorflow_datasets/leaf_classification/1.0.1',
    file_format=tfrecord,
    download_size=Unknown size,
    dataset_size=2.60 MiB,
    features=FeaturesDict({
        'image': Image(shape=(224, 224, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=15),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test_images': <SplitInfo num_examples=100, num_shards=1>,
    },
    citation="""""",
)

In [174]:
for data in ds:
  print(data)
  break

{'image': <tf.Tensor: shape=(224, 224, 3), dtype=uint8, numpy=
array([[[190, 189, 195],
        [190, 189, 195],
        [190, 189, 195],
        ...,
        [185, 188, 193],
        [184, 187, 192],
        [184, 187, 192]],

       [[190, 189, 195],
        [190, 189, 195],
        [190, 189, 195],
        ...,
        [185, 188, 193],
        [184, 187, 192],
        [184, 187, 192]],

       [[190, 189, 195],
        [190, 189, 195],
        [190, 189, 195],
        ...,
        [185, 188, 193],
        [184, 187, 192],
        [184, 187, 192]],

       ...,

       [[184, 183, 189],
        [184, 183, 189],
        [184, 183, 189],
        ...,
        [178, 182, 185],
        [179, 183, 186],
        [179, 183, 186]],

       [[184, 183, 189],
        [184, 183, 189],
        [184, 183, 189],
        ...,
        [178, 182, 185],
        [179, 182, 187],
        [179, 182, 187]],

       [[184, 183, 189],
        [184, 183, 189],
        [184, 183, 189],
        ...,
        [17

In [81]:
from pathlib import Path
from collections import Counter

path = Path('full')

temp = Counter([os.path.basename(os.path.dirname(l)) for l in path.glob('*/*/*.*')])
{k:v for (v,k) in enumerate(temp.keys())}

{'croped_Calcarious soil symptoms': 0,
 'croped_Caterpillar Damage': 1,
 'croped_Mite infestation': 2,
 'croped_Powdery mildew white background': 3,
 'cropped_Anthracnose leaves white background': 4,
 'cropped_Anthracnose natural background': 5,
 'cropped_Downy mildew': 6,
 'cropped_Jassid damage': 7,
 'cropped_k deficiency white background': 8,
 'cropped_Mealybug leaf malformation': 9,
 'cropped_Powdery mildew natural background': 10,
 'cropped_Thrips curling': 11,
 'cropped_Zn toxicity': 12,
 'Deficiency symptoms on grapes -Not identified': 13,
 'Downy mildew photos': 14}

In [86]:
[l for l in path.glob('*/*/*.*') if 'jpg' not in str(l) and 'JPG' not in str(l)]

[PosixPath('full/leaf_cropped_images/Deficiency symptoms on grapes -Not identified/Thumbs.db')]

In [90]:
cd ..

/content


In [91]:
!cp -r '/content/full/leaf_cropped_images/cropped_k deficiency white background' '/content/full/test_images'

cp: cannot create regular file '/content/full/test_images/cropped_k deficiency white background/DSC_2144.JPG': File exists
cp: cannot create regular file '/content/full/test_images/cropped_k deficiency white background/DSC_2172.JPG': File exists
cp: cannot create regular file '/content/full/test_images/cropped_k deficiency white background/DSC_2198.JPG': File exists
cp: cannot create regular file '/content/full/test_images/cropped_k deficiency white background/DSC_2201.JPG': File exists
cp: cannot create regular file '/content/full/test_images/cropped_k deficiency white background/DSC_2258.JPG': File exists
cp: cannot create regular file '/content/full/test_images/cropped_k deficiency white background/DSC_2268.JPG': File exists
^C


In [166]:
all_files = [p for p in os.listdir('/content/full/test_images/cropped_k deficiency white background') if 'resized' in p]

In [168]:
im_path = '/content/full/test_images/cropped_k deficiency white background/resized_DSC_2112.JPG'
im = tf.keras.utils.load_img(str(im_path))

(3232, 3104)

In [169]:
im = im.resize((224, 224), resample=3)
im.size


(224, 224)

In [167]:
all_files

['resized_DSC_2112.JPG',
 'resized_DSC_2526.JPG',
 'resized_DSC_2548.JPG',
 'resized_DSC_2178.JPG',
 'resized_DSC_1783.JPG',
 'resized_DSC_2578.JPG',
 'resized_DSC_2380.JPG',
 'resized_DSC_1688.JPG',
 'resized_DSC_1840.JPG',
 'resized_DSC_2580.JPG',
 'resized_DSC_2294.JPG',
 'resized_DSC_2137.JPG',
 'resized_DSC_2460.JPG',
 'resized_DSC_2480.JPG',
 'resized_DSC_2453.JPG',
 'resized_DSC_2310.JPG',
 'resized_DSC_2586.JPG',
 'resized_DSC_2405.JPG',
 'resized_DSC_1912.JPG',
 'resized_DSC_2289.JPG',
 'resized_DSC_2468.JPG',
 'resized_DSC_2191.JPG',
 'resized_DSC_1806.JPG',
 'resized_DSC_2351.JPG',
 'resized_DSC_1752.JPG',
 'resized_DSC_1866.JPG',
 'resized_DSC_2397.JPG',
 'resized_DSC_2072.JPG',
 'resized_DSC_2486.JPG',
 'resized_DSC_2256.JPG',
 'resized_DSC_2702.JPG',
 'resized_DSC_2314.JPG',
 'resized_DSC_2076.JPG',
 'resized_DSC_2407.JPG',
 'resized_DSC_1808.JPG',
 'resized_DSC_2422.JPG',
 'resized_DSC_2531.JPG',
 'resized_DSC_2281.JPG',
 'resized_DSC_2411.JPG',
 'resized_DSC_1859.JPG',


In [136]:
cd ..

/content


In [139]:
import tensorflow as tf
img_path = Path('full/test_images/cropped_k deficiency white background/DSC_2622.JPG')
im = tf.keras.utils.load_img(str(img_path))
im.size

(2664, 2616)